force-window-position=yes
script-opts-append=osc-idlescreen=no
ontop=yes
# --- WINDOW SIZE ---
# Limits the maximum window size to 50% of your screen's width and height.
# You can change "50%" to "30%" or "40%" depending on how small you want it.
autofit-larger=36%x36% 

# --- BORDERS ---
# Disables the Windows/Mac/Linux window borders and title bar
border=no

# --- ASPECT RATIO ---
# Forces the player to keep the media's original aspect ratio (MPV does this by default)
keepaspect=yes
# Prevents you from resizing the window into weird, stretched shapes
keepaspect-window=yes

#2-second fade and bottom bar layout
script-opts-append=osc-fadeduration=2000
script-opts-append=osc-layout=bottombar

# --- CUSTOM FONT SETTINGS ---

# Changes the main UI and OSD text font
osd-font="Ableton Sans Small"

# (Optional) Changes the subtitle font to match, if you ever play videos
sub-font="Ableton Sans Small"

# (Optional) Make the font look cleaner and modern
osd-scale=1.5
osd-font-size=25
osd-border-size=2          # Makes the black outline a bit thinner
osd-color="#FFFFFF"        # Pure white text
osd-border-color="#000000" # Pure black outline

keep-open=yes
